stages:          # List of stages for jobs, and their order of execution
  - test


test-job:
  image: git.igd-r.fraunhofer.de:4567/digit/digit-base-ui:latest
  stage: test
  tags:
    - ubuntu
  variables:
    GIT_SUBMODULE_STRATEGY: recursive
    STATIC_PATH: $CI_PROJECT_DIR/static
    ROOT_PATH:   $CI_PROJECT_DIR
    PYTHONPATH:  $CI_PROJECT_DIR
  script:
    - ls -a
    - ls $ROOT_PATH/templates
    - pwd
    - env | grep `pwd`
    - ./run_tests.sh -x
