name: CI

on:
  push:
    branches: [ "preact" ]

  workflow_dispatch:

env:
  NO_COLOR: "true"


jobs:
  unittests:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Cache deno dependencies
        run: |
          ./deno.sh task cache

      - name: Deno check
        run: |
          ./deno.sh check frontend/ts/index.tsx

      - name: Run unit tests
        id:   unittests
        run: |
          ./deno.sh test                  \
              --allow-read=.,/tmp         \
              --allow-write=/tmp          \
              --no-prompt                 \
              --cached-only               \
              --no-check

